spring:
  profiles:
    active: prod

  application:
    name: dxboot

  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO